defaults:
  - multi_rew_dmc_env

name: humanoid-run
domain_name: humanoid
task_name: run
num_envs: ${train.num_seeds}
seed: ${train.seed}
action_noise: false
action_noise_type: normal
action_noise_level: 0.0
frame_skip: 2
num_distractions: 0
obs_distortion: False
noise_distraction: False
state_shape: 0