defaults:
  - train: crossent_byol_vaml
  - algo: base_mad_td
  - env: maniskill
  - models: td_mpc2
  - logger: wandb
  - _self_

debug: False
name: mad_td
name_template: "{critic}-{mpc}-{mb}-{model-loss-short}-{mfenc}"

cluster_checkpointing: False
alt_path: .

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
